In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("F:/more work/the netherlands/tt data/Wave5_DiaryID_car_bike_walk_transit_traveltimes_anonymous.csv",sep=";")

In [7]:
df

,DiaryID,Time_driv,Time_traffic_driv,Dist_driv,Status_driv,Time_bike,Dist_bike,Status_bike,Time_walk,Dist_walk,Status_walk,Dist_transit,Time_transit,Status_transit,Only_walking_transit
0,530190,543.0,507.0,4287.0,OK,821.0,4425.0,OK,2870.0,3901.0,OK,5347.0,1001.0,OK,0.0
1,530192,508.0,480.0,4290.0,OK,849.0,4417.0,OK,2866.0,3901.0,OK,5269.0,1012.0,OK,0.0
2,530194,433.0,425.0,3574.0,OK,508.0,2761.0,OK,1848.0,2527.0,OK,4541.0,1021.0,OK,0.0
3,530199,187.0,184.0,1114.0,OK,233.0,1112.0,OK,840.0,1091.0,OK,1091.0,840.0,OK,1.0
4,530203,2359.0,2397.0,55367.0,OK,7747.0,41541.0,OK,23039.0,32213.0,OK,47468.0,5871.0,OK,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44292,666714,651.0,648.0,6047.0,OK,1397.0,6105.0,OK,4335.0,5777.0,OK,9678.0,1769.0,OK,0.0
44293,666716,1248.0,1237.0,26777.0,OK,4363.0,23897.0,OK,16871.0,23157.0,OK,37415.0,8406.0,OK,0.0
44294,666727,1293.0,1240.0,26248.0,OK,4746.0,25759.0,OK,16222.0,22317.0,OK,59378.0,7245.0,OK,0.0
44295,666730,3750.0,3641.0,74415.0,OK,11520.0,62621.0,OK,42013.0,57309.0,OK,128205.0,9120.0,OK,0.0
44296,666732,3678.0,3868.0,73512.0,OK,11356.0,62344.0,OK,42106.0,57344.0,OK,128834.0,9228.0,OK,0.0

df